
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'Been' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'Google-Mobile-Ads-SDK','~> 7.69.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.2.1.0'
  pod 'react-native-heic-converter', :path => '../node_modules/react-native-heic-converter'


  # pod 'Google-Mobile-Ads-SDK', '8.7.0'
  
 
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }) 
  use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})
  
  post_install do |installer|
    flipper_post_install(installer)
  end
end
